### ISSUE TITLE
Make bundle compatible with SF3.0

### ISSUE THREAD

**Issue by helios-ag** [helios-ag/FMBbCodeBundle#130]

**Comment by alquerci** [comment]
@helios-ag Need to create a dedicated branch for that.

**Comment by doppynl** [comment]
Is there any progress on this? What is preventing the version bump to 3.0?

**Comment by GuillaumeHemmen** [comment]
Hi @helios-ag any news about this issue? I'm really impatient to re-use your bundle into my websites.

**Comment by helios-ag** [comment]
Hi @doppynl and @GuillaumeHemmen looks like @alquerci is working on it https://github.com/alquerci/FMBbCodeBundle/commits/fix-versioning . There is also 3.0  branch of the bundle, which should work too, you can download it with 'dev-3.0' version constraint in composer.json

**Comment by helios-ag** [comment]
see also #136

**Comment by GuillaumeHemmen** [comment]
cheers @helios-ag !

**Comment by helios-ag** [comment]
Tagged as 7.0

**Comment by alquerci** [comment]
On the readme of the branch 3.0 there is a good base:
:+1: @helios-ag 

For symfony <3.0, use latest major version 6

``` sh
composer require helios-ag/fm-bbcode-bundle:^6
```

for Symfony 3

``` sh
composer require helios-ag/fm-bbcode-bundle:^7
```

Ref from the composer doc for using `^` instead of `~` https://getcomposer.org/doc/articles/versions.md#caret

---

We should use the Symfony development process https://youtu.be/qlrwfOL0230?t=16m50s
But maybe just using one branch for each major version instead of minor one.

**Comment by helios-ag** [comment]
Thank you @alquerci for sharing Fabien's speech. I will update readme accordingly. And separate branches for majors looks fine for me. But versioning for this bundle wasn't followed semantic versioning before (i synced it with decoda's lib).

**Comment by ghost** [comment]
I think that ticket can be closed, correct?

**Comment by helios-ag** [comment]
@hipio seems so, thanks!
